# Generated by Django 5.2.6 on 2025-11-05 18:27

import django.db.models.deletion
import django.utils.timezone
import tickets.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.AlterModelOptions(
            name='assignmentrule',
            options={'ordering': ['-is_active', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='beforeafterphoto',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ticketstatushistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='departments_org_cod_0a2c05_idx',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='departments_dep_cod_617004_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_status_f67985_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_categor_c68ffb_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_priorit_169cf7_idx',
        ),
        migrations.RenameField(
            model_name='ticketstatushistory',
            old_name='comment',
            new_name='note',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_tic_assigne_e36302_idx',
            old_name='tickets_assigne_fc2b2b_idx',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='beforeafterphoto',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='beforeafterphoto',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='department',
            name='dep_code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='dep_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='last_synced',
        ),
        migrations.RemoveField(
            model_name='department',
            name='org_code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='org_name_en',
        ),
        migrations.RemoveField(
            model_name='department',
            name='org_name_th',
        ),
        migrations.RemoveField(
            model_name='ticketfeedback',
            name='cleanliness_rating',
        ),
        migrations.RemoveField(
            model_name='ticketfeedback',
            name='overall_rating',
        ),
        migrations.RemoveField(
            model_name='ticketfeedback',
            name='politeness_rating',
        ),
        migrations.RemoveField(
            model_name='ticketfeedback',
            name='response_speed_rating',
        ),
        migrations.RemoveField(
            model_name='ticketfeedback',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='ticketfeedback',
            name='work_quality_rating',
        ),
        migrations.RemoveField(
            model_name='ticketstatushistory',
            name='new_status',
        ),
        migrations.RemoveField(
            model_name='ticketstatushistory',
            name='old_status',
        ),
        migrations.RemoveField(
            model_name='ticketstatushistory',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='assignmentrule',
            name='name',
            field=models.CharField(default='Default Rule', max_length=120),
        ),
        migrations.AddField(
            model_name='beforeafterphoto',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticketfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='ticketstatushistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticketstatushistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('INSPECTING', 'ตรวจสอบหน้างาน'), ('WORKING', 'ลงมือแก้ไข'), ('COMPLETED', 'เสร็จสิ้น'), ('CLOSED', 'ปิดงาน'), ('REJECTED', 'ปฏิเสธงาน')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='assignmentrule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assignmentrule',
            name='max_open_tickets',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='assignmentrule',
            name='weight_distance',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='assignmentrule',
            name='weight_workload',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=tickets.models.attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beforeafterphoto',
            name='image',
            field=models.ImageField(upload_to=tickets.models.photo_upload_to),
        ),
        migrations.AlterField(
            model_name='beforeafterphoto',
            name='photo_type',
            field=models.CharField(choices=[('BEFORE', 'ก่อนซ่อม'), ('AFTER', 'หลังซ่อม')], max_length=6),
        ),
        migrations.AlterField(
            model_name='beforeafterphoto',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='technicianpresence',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='technicianpresence',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='technicianpresence',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.category'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('INSPECTING', 'ตรวจสอบหน้างาน'), ('WORKING', 'ลงมือแก้ไข'), ('COMPLETED', 'เสร็จสิ้น'), ('CLOSED', 'ปิดงาน'), ('REJECTED', 'ปฏิเสธงาน')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='urgency_level',
            field=models.CharField(choices=[('LOW', 'ต่ำ'), ('MEDIUM', 'ปานกลาง'), ('HIGH', 'สูง'), ('CRITICAL', 'วิกฤติ')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticketfeedback',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticketfeedback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticketfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketstatushistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_histories', to='tickets.ticket'),
        ),
        migrations.AddIndex(
            model_name='beforeafterphoto',
            index=models.Index(fields=['ticket', 'photo_type'], name='tickets_bef_ticket__3c6bed_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianpresence',
            index=models.Index(fields=['technician'], name='tickets_tec_technic_138ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianpresence',
            index=models.Index(fields=['latitude', 'longitude'], name='tickets_tec_latitud_331b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianpresence',
            index=models.Index(fields=['is_available'], name='tickets_tec_is_avai_f915c2_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['latitude', 'longitude'], name='tickets_tic_latitud_ab880f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['category'], name='tickets_tic_categor_3266ff_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketstatushistory',
            index=models.Index(fields=['ticket', 'status'], name='tickets_tic_ticket__f37416_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketstatushistory',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_ab406e_idx'),
        ),
        migrations.AlterModelTable(
            name='assignmentrule',
            table=None,
        ),
        migrations.AlterModelTable(
            name='attachment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='beforeafterphoto',
            table=None,
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='department',
            table=None,
        ),
        migrations.AlterModelTable(
            name='technicianpresence',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ticket',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ticketfeedback',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ticketstatushistory',
            table=None,
        ),
    ]
