# Generated by Django 5.2.7 on 2025-11-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_backfill_department_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketFeedback',
        ),
    ]
